version: '3.7'

x-node-env: &node-env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-service: &node-service
  tty: true
  init: true
  image: node:16.13-alpine
  working_dir: /cms-apis
  volumes:
    - .:/cms-apis:cached
    - ./node_modules:/cms-apis/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *node-env

x-env-mongodb: &mongodb-env
  MONGO_URL: ${MONGO_URL-mongodb://root:password123@mongodb-primary:27017,mongodb-secondary:27017/?authSource=admin&readPreference=primary}

x-env-legacy-mongodb: &legacy-mongodb-env
  LEGACY_MONGO_URL: ${LEGACY_MONGO_URL-mongodb://mongodb-legacy:27017}

services:
  commands:
    <<: *node-service
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  graphql:
    <<: *node-service
    working_dir: /cms-apis/apis/graphql
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *node-env
      <<: *legacy-mongodb-env
      EXPOSED_HOST: cms-apis-graphql.dev.parameter1.com
      EXPOSED_PORT: 11760
      HOST: cms-apis-graphql.dev.parameter1.com
      SHUTDOWN_GRACE_PERIOD: 0
    hostname: cms-apis-graphql.dev.parameter1.com
    ports:
      - "11760:80"
    depends_on:
      - mongodb-legacy

  rest:
    <<: *node-service
    working_dir: /cms-apis/apis/legacy-rest
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *node-env
      <<: *mongodb-env
      EXPOSED_HOST: cms-apis-rest.dev.parameter1.com
      EXPOSED_PORT: 11761
      HOST: cms-apis-rest.dev.parameter1.com
      SHUTDOWN_GRACE_PERIOD: 0
    hostname: cms-apis-rest.dev.parameter1.com
    ports:
      - "11761:80"
    depends_on:
      - mongodb-secondary

  transformer-cli:
    <<: *node-service
    working_dir: /cms-apis/packages/model-transformers
    entrypoint: ["node"]
    command: ["src"]
    environment:
      <<: *node-env
      <<: *mongodb-env
      <<: *legacy-mongodb-env
    depends_on:
      - mongodb-legacy
      - mongodb-secondary

  mongodb-legacy:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb-legacy:/data/db
    ports:
      - "11660:27017"

  mongodb-primary:
    image: bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=cmsapis
    volumes:
      - mongodb-primary:/bitnami
    ports:
      - "11661:27017"

  mongodb-secondary:
    image: bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=cmsapis
    volumes:
      - mongodb-secondary:/bitnami

volumes:
  mongodb-primary: {}
  mongodb-secondary: {}
  mongodb-legacy: {}
  yarn-cache: {}
