import { fromJS } from '@cms-apis/immutable';

export default fromJS({
  content: {
    ARTICLE: 'Article',
    BLOG: 'Blog',
    COMPANY: 'Company',
    CONTACT: 'Contact',
    DOCUMENT: 'Document',
    EVENT: 'Event',
    JOB: 'Job',
    MEDIA_GALLERY: 'MediaGallery',
    NEWS: 'News',
    PAGE: 'Page',
    PODCAST: 'Podcast',
    PRESS_RELEASE: 'PressRelease',
    PRODUCT: 'Product',
    PROMOTION: 'Promotion',
    SPACE: 'Space',
    SUPPLIER: 'Supplier',
    TEXT_AD: 'TextAd',
    VENUE: 'Venue',
    VIDEO: 'Video',
    WEBINAR: 'Webinar',
    WHITEPAPER: 'Whitepaper',
  },
  taxonomy: {
    AWARD: 'Award',
    BADGE: 'Badge',
    BIN: 'Bin',
    CATEGORY: 'Category',
    INDUSTRY: 'Industry',
    LOCATION: 'Location',
    MARKET: 'Market',
    ORGANIZATION: 'Organization',
    PERSON: 'Person',
    PLATFORM_CHANNEL: 'PlatformChannel',
    REGION: 'Region',
    SYSTEM: 'System',
    TAG: 'Tag',
    TOPIC: 'Topic',
    TYPE: 'Type',
  },
});
